package timediff_test

import (
	"fmt"
	"testing"

	"github.com/mergestat/timediff"
)

var fixtures_fr_FR = map[string]string{
	"-10s":                            "il y a quelques secondes",
	"-44s":                            "il y a quelques secondes",
	"-45s":                            "il y a une minute",
	"-89s":                            "il y a une minute",
	"-90s":                            "il y a 2 minutes",
	"-91s":                            "il y a 2 minutes",
	"-2m":                             "il y a 2 minutes",
	"-10m":                            "il y a 10 minutes",
	"-44m":                            "il y a 44 minutes",
	"-45m":                            "il y a une heure",
	"-60m":                            "il y a une heure",
	"-1h":                             "il y a une heure",
	"-80m":                            "il y a une heure",
	"-89m":                            "il y a une heure",
	"-90m":                            "il y a 2 heures",
	"-2h":                             "il y a 2 heures",
	"-20h":                            "il y a 20 heures",
	"-21h":                            "il y a 21 heures",
	"-21h30m":                         "il y a un jour",
	"-22h":                            "il y a un jour",
	"-24h":                            "il y a un jour",
	"-24h30m":                         "il y a un jour",
	"-34h59m":                         "il y a un jour",
	"-36h":                            "il y a 2 jours",
	fmt.Sprintf("-%dh", 10*24):        "il y a 10 jours",
	fmt.Sprintf("-%dh", 25*24):        "il y a 25 jours",
	fmt.Sprintf("-%dh", 26*24):        "il y a un mois",
	fmt.Sprintf("-%dh", 45*24):        "il y a un mois",
	fmt.Sprintf("-%dh2m", 45*24):      "il y a 2 mois",
	fmt.Sprintf("-%dh", 46*24+1):      "il y a 2 mois",
	fmt.Sprintf("-%dh", 80*24):        "il y a 3 mois",
	fmt.Sprintf("-%dh", 9*24*30):      "il y a 9 mois",
	fmt.Sprintf("-%dh", 10*24*30):     "il y a 10 mois",
	fmt.Sprintf("-%dh1m", 10*24*30):   "il y a un an",
	fmt.Sprintf("-%dh", 12*24*30):     "il y a un an",
	fmt.Sprintf("-%dh", 17*24*30+1):   "il y a 2 ans",
	fmt.Sprintf("-%dh", 24*24*30):     "il y a 2 ans",
	fmt.Sprintf("-%dh", 20*24*30*12):  "il y a 20 ans",
	fmt.Sprintf("-%dh", 100*24*30*12): "il y a 100 ans",

	"10s":                            "dans quelques secondes",
	"44s":                            "dans quelques secondes",
	"45s":                            "dans une minute",
	"89s":                            "dans une minute",
	"90s":                            "dans 2 minutes",
	"2m":                             "dans 2 minutes",
	"10m":                            "dans 10 minutes",
	"44m":                            "dans 44 minutes",
	"45m":                            "dans une heure",
	"60m":                            "dans une heure",
	"1h":                             "dans une heure",
	"80m":                            "dans une heure",
	"89m":                            "dans une heure",
	"89m10s":                         "dans 2 heures",
	"90m":                            "dans 2 heures",
	"2h":                             "dans 2 heures",
	"20h":                            "dans 20 heures",
	"21h":                            "dans 21 heures",
	"21h30m":                         "dans un jour",
	"22h":                            "dans un jour",
	"24h":                            "dans un jour",
	"35h10m":                         "dans 2 jours",
	"36h":                            "dans 2 jours",
	fmt.Sprintf("%dh", 10*24):        "dans 10 jours",
	fmt.Sprintf("%dh", 25*24):        "dans 25 jours",
	fmt.Sprintf("%dh", 26*24):        "dans un mois",
	fmt.Sprintf("%dh", 45*24):        "dans un mois",
	fmt.Sprintf("%dh1m", 45*24):      "dans 2 mois",
	fmt.Sprintf("%dh", 46*24):        "dans 2 mois",
	fmt.Sprintf("%dh", 80*24):        "dans 3 mois",
	fmt.Sprintf("%dh", 9*24*30):      "dans 9 mois",
	fmt.Sprintf("%dh", 10*24*30):     "dans 10 mois",
	fmt.Sprintf("%dh1m", 10*24*30):   "dans un an",
	fmt.Sprintf("%dh", 12*24*30):     "dans un an",
	fmt.Sprintf("%dh", 24*24*30):     "dans 2 ans",
	fmt.Sprintf("%dh", 20*24*30*12):  "dans 20 ans",
	fmt.Sprintf("%dh", 100*24*30*12): "dans 100 ans",
}

func TestTimeDiffFrFR(t *testing.T) {
	execFixtures(t, fixtures_fr_FR, timediff.WithLocale("fr-FR"))
}
