package timediff_test

import (
	"fmt"
	"testing"

	"github.com/mergestat/timediff"
)

var fixtures_id_ID = map[string]string{
	"-10s":                            "beberapa detik yang lalu",
	"-44s":                            "beberapa detik yang lalu",
	"-45s":                            "satu menit yang lalu",
	"-89s":                            "satu menit yang lalu",
	"-90s":                            "2 menit yang lalu",
	"-91s":                            "2 menit yang lalu",
	"-2m":                             "2 menit yang lalu",
	"-10m":                            "10 menit yang lalu",
	"-44m":                            "44 menit yang lalu",
	"-45m":                            "satu jam yang lalu",
	"-60m":                            "satu jam yang lalu",
	"-1h":                             "satu jam yang lalu",
	"-80m":                            "satu jam yang lalu",
	"-89m":                            "satu jam yang lalu",
	"-90m":                            "2 jam yang lalu",
	"-2h":                             "2 jam yang lalu",
	"-20h":                            "20 jam yang lalu",
	"-21h":                            "21 jam yang lalu",
	"-21h30m":                         "sehari yang lalu",
	"-22h":                            "sehari yang lalu",
	"-24h":                            "sehari yang lalu",
	"-24h30m":                         "sehari yang lalu",
	"-34h59m":                         "sehari yang lalu",
	"-36h":                            "2 hari yang lalu",
	fmt.Sprintf("-%dh", 10*24):        "10 hari yang lalu",
	fmt.Sprintf("-%dh", 25*24):        "25 hari yang lalu",
	fmt.Sprintf("-%dh", 26*24):        "sebulan yang lalu",
	fmt.Sprintf("-%dh", 45*24):        "sebulan yang lalu",
	fmt.Sprintf("-%dh2m", 45*24):      "2 bulan yang lalu",
	fmt.Sprintf("-%dh", 46*24+1):      "2 bulan yang lalu",
	fmt.Sprintf("-%dh", 80*24):        "3 bulan yang lalu",
	fmt.Sprintf("-%dh", 9*24*30):      "9 bulan yang lalu",
	fmt.Sprintf("-%dh", 10*24*30):     "10 bulan yang lalu",
	fmt.Sprintf("-%dh1m", 10*24*30):   "setahun yang lalu",
	fmt.Sprintf("-%dh", 12*24*30):     "setahun yang lalu",
	fmt.Sprintf("-%dh", 17*24*30+1):   "2 tahun yang lalu",
	fmt.Sprintf("-%dh", 24*24*30):     "2 tahun yang lalu",
	fmt.Sprintf("-%dh", 20*24*30*12):  "20 tahun yang lalu",
	fmt.Sprintf("-%dh", 100*24*30*12): "100 tahun yang lalu",

	"10s":                            "dalam beberapa detik",
	"44s":                            "dalam beberapa detik",
	"45s":                            "dalam satu menit",
	"89s":                            "dalam satu menit",
	"90s":                            "dalam 2 menit",
	"2m":                             "dalam 2 menit",
	"10m":                            "dalam 10 menit",
	"44m":                            "dalam 44 menit",
	"45m":                            "dalam satu jam",
	"60m":                            "dalam satu jam",
	"1h":                             "dalam satu jam",
	"80m":                            "dalam satu jam",
	"89m":                            "dalam satu jam",
	"89m10s":                         "dalam 2 jam",
	"90m":                            "dalam 2 jam",
	"2h":                             "dalam 2 jam",
	"20h":                            "dalam 20 jam",
	"21h":                            "dalam 21 jam",
	"21h30m":                         "dalam sehari",
	"22h":                            "dalam sehari",
	"24h":                            "dalam sehari",
	"35h10m":                         "dalam 2 hari",
	"36h":                            "dalam 2 hari",
	fmt.Sprintf("%dh", 10*24):        "dalam 10 hari",
	fmt.Sprintf("%dh", 25*24):        "dalam 25 hari",
	fmt.Sprintf("%dh", 26*24):        "dalam sebulan",
	fmt.Sprintf("%dh", 45*24):        "dalam sebulan",
	fmt.Sprintf("%dh1m", 45*24):      "dalam 2 bulan",
	fmt.Sprintf("%dh", 46*24):        "dalam 2 bulan",
	fmt.Sprintf("%dh", 80*24):        "dalam 3 bulan",
	fmt.Sprintf("%dh", 9*24*30):      "dalam 9 bulan",
	fmt.Sprintf("%dh", 10*24*30):     "dalam 10 bulan",
	fmt.Sprintf("%dh1m", 10*24*30):   "dalam setahun",
	fmt.Sprintf("%dh", 12*24*30):     "dalam setahun",
	fmt.Sprintf("%dh", 24*24*30):     "dalam 2 tahun",
	fmt.Sprintf("%dh", 20*24*30*12):  "dalam 20 tahun",
	fmt.Sprintf("%dh", 100*24*30*12): "dalam 100 tahun",
}

func TestTimeDiffIdID(t *testing.T) {
	execFixtures(t, fixtures_id_ID, timediff.WithLocale("id-ID"))
}
